### ISSUE TITLE
API v4 broke the pkgbot

### ISSUE THREAD

**Issue by fujexo** [adfinis/gitlab-pkgbot#11]
```
Jun 28 20:24:48 sr-adsy-mirrors-02 gitlab-pkgbot[583]: Exception in thread Thread-122:
Jun 28 20:24:48 sr-adsy-mirrors-02 gitlab-pkgbot[583]: Traceback (most recent call last):
Jun 28 20:24:48 sr-adsy-mirrors-02 gitlab-pkgbot[583]: File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
Jun 28 20:24:48 sr-adsy-mirrors-02 gitlab-pkgbot[583]: self.run()
Jun 28 20:24:48 sr-adsy-mirrors-02 gitlab-pkgbot[583]: File "/usr/lib/python2.7/threading.py", line 763, in run
Jun 28 20:24:48 sr-adsy-mirrors-02 gitlab-pkgbot[583]: self.__target(*self.__args, **self.__kwargs)
Jun 28 20:24:48 sr-adsy-mirrors-02 gitlab-pkgbot[583]: File "build/bdist.linux-x86_64/egg/pkgbot/__init__.py", line 195, in process_request
Jun 28 20:24:48 sr-adsy-mirrors-02 gitlab-pkgbot[583]: git.select_project(data['project_id'])
Jun 28 20:24:48 sr-adsy-mirrors-02 gitlab-pkgbot[583]: File "build/bdist.linux-x86_64/egg/pkgbot/GitlabHelper.py", line 35, in select_project
Jun 28 20:24:48 sr-adsy-mirrors-02 gitlab-pkgbot[583]: self.project = self.git.projects.get(project_id)
Jun 28 20:24:48 sr-adsy-mirrors-02 gitlab-pkgbot[583]: File "/usr/local/lib/python2.7/dist-packages/gitlab/objects.py", line 102, in get
Jun 28 20:24:48 sr-adsy-mirrors-02 gitlab-pkgbot[583]: return self.obj_cls.get(self.gitlab, id, **args)
Jun 28 20:24:48 sr-adsy-mirrors-02 gitlab-pkgbot[583]: File "/usr/local/lib/python2.7/dist-packages/gitlab/objects.py", line 276, in get
Jun 28 20:24:48 sr-adsy-mirrors-02 gitlab-pkgbot[583]: return cls(gl, id, **kwargs)
Jun 28 20:24:48 sr-adsy-mirrors-02 gitlab-pkgbot[583]: File "/usr/local/lib/python2.7/dist-packages/gitlab/objects.py", line 380, in __init__
Jun 28 20:24:48 sr-adsy-mirrors-02 gitlab-pkgbot[583]: data = self.gitlab.get(self.__class__, data, **kwargs)
Jun 28 20:24:48 sr-adsy-mirrors-02 gitlab-pkgbot[583]: File "/usr/local/lib/python2.7/dist-packages/gitlab/__init__.py", line 425, in get
Jun 28 20:24:48 sr-adsy-mirrors-02 gitlab-pkgbot[583]: raise_error_from_response(r, GitlabGetError)
Jun 28 20:24:48 sr-adsy-mirrors-02 gitlab-pkgbot[583]: File "/usr/local/lib/python2.7/dist-packages/gitlab/exceptions.py", line 180, in raise_error_from_response
Jun 28 20:24:48 sr-adsy-mirrors-02 gitlab-pkgbot[583]: response_body=response.content)
Jun 28 20:24:48 sr-adsy-mirrors-02 gitlab-pkgbot[583]: GitlabGetError: 410: {"error":"API V3 is no longer supported. Use API V4 instead."}
```

**Comment by fujexo** [comment]
I have now updated the python-gitlab library to version 1.5.1. The above error is gone but a new one appeared:

```
Jun 28 20:38:38 sr-adsy-mirrors-02 systemd[1]: Starting adsy gitlab pkgbot...
Jun 28 20:38:38 sr-adsy-mirrors-02 systemd[1]: Started adsy gitlab pkgbot.
Jun 28 20:38:38 sr-adsy-mirrors-02 gitlab-pkgbot[12322]: 2018-06-28 20:38:38,517 - adsy-pkgbot - INFO - Started 1.0.1 server on port 8084
Jun 28 20:39:17 sr-adsy-mirrors-02 gitlab-pkgbot[12322]: 2018-06-28 20:39:17,995 - adsy-pkgbot - INFO - REQUEST: POST / HTTP/1.0 200 -
Jun 28 20:39:19 sr-adsy-mirrors-02 gitlab-pkgbot[12322]: 2018-06-28 20:39:19,128 - adsy-pkgbot - INFO - REQUEST: POST / HTTP/1.0 200 -
Jun 28 20:39:35 sr-adsy-mirrors-02 gitlab-pkgbot[12322]: 2018-06-28 20:39:35,251 - adsy-pkgbot - INFO - ad-sy/adfinis-dirvish.src - Process build trigger
Jun 28 20:39:35 sr-adsy-mirrors-02 gitlab-pkgbot[12322]: 2018-06-28 20:39:35,253 - adsy-pkgbot - INFO - REQUEST: POST / HTTP/1.0 200 -
Jun 28 20:39:35 sr-adsy-mirrors-02 gitlab-pkgbot[12322]: 2018-06-28 20:39:35,274 - adsy-pkgbot - ERROR - ad-sy/adfinis-dirvish.src - Config for repo not found or invalid
```
Better error checking would help: https://github.com/adfinis-sygroup/gitlab-pkgbot/blob/18ac32b84907d97c4e98418c762194a3fc1392dd/pkgbot/__init__.py#L63
